### ISSUE TITLE
Application Launch

### ISSUE THREAD

**Issue by Ankur-prasun** [saikatbsk/Ishara#11]
Sir,
I have successfully installed your code.I am able to run Ishara application . I am using VMware and on launching the app,my inbuilt webcam  and the launching window of application opens.The problem  i am facing is that on clicking start,the screen of the window(application) remains blank and the system starts hanging.
I have seen three options on the top left corner of the application window i.e. FILE etc.
I want to ask how to start the functionality of the program.I have to simple click on start or have to do something else for movement of mouse with the fingers(including markers).
Please reply at the earliest
Regards

**Comment by Ankur-prasun** [comment]
Sir,
Kindly provide with the solution.What will be procedure to run the program.

**Comment by saikatbsk** [comment]
Go to configure tab and adjust the H, S, V values to detect your color markers. Then you can start/stop the detection either from the main tab or by pressing F9.

**Comment by Arukurchi** [comment]
Sir,
I am using Ubuntu in VMWare and its not working properly. Could you please suggest me a solution.
Also I am not being able to put the minimum and the maximum values of H,S,V of red and blue colours.

**Comment by Ankur-prasun** [comment]
What will be the minimu and maximum value for HSV? I am getting only one values for h,s,v. respectively

**Comment by saikatbsk** [comment]
H, S, V, values may change depending on the lighting conditions. Use a red ball or something like that and play with the min/max hsv values. If you see any white blob where the ball is, then you may know that the hsv values are optimized for red.

**Comment by Ankur-prasun** [comment]
Sir, i am able to find the h,s,v value for red color as instructed by you but in the case of blue ,black blob is appearing. Can i use 2 red markers instead of one blue and one red ?

**Comment by saikatbsk** [comment]
No, you cannot. You need two different colors. If red isn't working for you go for green, or something like that.
