### ISSUE TITLE
‘CV_BGR2HSV’ not declared

### ISSUE THREAD

**Issue by S73ph4n** [saikatbsk/Ishara#9]
I got the following error trying to install Ishara.
I googled it and was unable to find anybody with the same problem...

stephan@orion:~/tmp/Ishara/build$ sudo make
[  9%] Generating qrc_res.cxx
[ 18%] Generating src/moc_ishara.cxx
[ 27%] Generating src/moc_aboutdialog.cxx
Scanning dependencies of target ishara
[ 36%] Building CXX object CMakeFiles/ishara.dir/src/main.cpp.o
[ 45%] Building CXX object CMakeFiles/ishara.dir/src/ishara.cpp.o
/home/stephan/tmp/Ishara/src/ishara.cpp: In member function ‘void ishara::processFrameAndUpdateGUI()’:
/home/stephan/tmp/Ishara/src/ishara.cpp:351:30: error: ‘CV_BGR2RGB’ was not declared in this scope
   cv::cvtColor(frame, frame, CV_BGR2RGB);
                              ^
/home/stephan/tmp/Ishara/src/ishara.cpp:356:31: error: ‘CV_BGR2HSV’ was not declared in this scope
   cv::cvtColor(frame, imgHSV, CV_BGR2HSV);
                               ^
/home/stephan/tmp/Ishara/src/ishara.cpp: In member function ‘void ishara::on_actionOriginal_triggered()’:
/home/stephan/tmp/Ishara/src/ishara.cpp:819:30: error: ‘CV_BGR2RGB’ was not declared in this scope
   cv::cvtColor(frame, frame, CV_BGR2RGB);
                              ^
CMakeFiles/ishara.dir/build.make:105: recipe for target 'CMakeFiles/ishara.dir/src/ishara.cpp.o' failed
make[2]: *** [CMakeFiles/ishara.dir/src/ishara.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/ishara.dir/all' failed
make[1]: *** [CMakeFiles/ishara.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
stephan@orion:~/tmp/Ishara/build$

**Comment by Beenking** [comment]
COLOR_BGR2HSV
